### ISSUE TITLE
Goal: Finish Chapter 1

### ISSUE THREAD

**Issue by alicerunsonfedora** [alicerunsonfedora/playgrounds-necessity-government#1]
@DireThunder, By the end of today at **_11:59 PM_**, we should have the following done:

## Task List
Note: will be updated in real time, checkmarks for each task.
1. [x] Thoroughly research the first topic: What is _government_? (Edit the wiki page to reflect research)
2. [x] Create the basic worlds to accommodate the task.
3. [x] Update the `Manifest.plist` in the playground chapter to reflect the changes.
4. [x] Debug and deploy!

**Comment by alicerunsonfedora** [comment]
The only section in this that I have to finish is the types of governments. Otherwise, I have the following completed:
* What is a government?
* How did governments form?
