### ISSUE TITLE
Goal: Finish Chapter 2

### ISSUE THREAD

**Issue by alicerunsonfedora** [alicerunsonfedora/playgrounds-necessity-government#2]
@DireThunder, we should have the following done for Chapter 2 (*Is the legislative branch necessary?*):

## Task List
Note: will be updated in real time, checkmarks for each task.
1. [x] Thoroughly research the first topic: What is _the legislative branch_? (Edit the wiki page to reflect research)
2. [ ] Investigate how to create world by looking at #1 .
3. [ ] Create the basic worlds to accommodate the task.
4. [ ] Update the `Manifest.plist` in the playground chapter to reflect the changes.
5. [ ] Debug and deploy!

Please complete this by **Wednesday, November 22, at 11:59 PM.**
